{
 "title": "Number of calls to endpoints",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_status_phase{namespace=~\"$namespace\",phase=\"Running\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "FastAPI Application Restart Count (Last 24 Hours)",
   "type": "stat",
   "gridPos": { "h": 15, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(resets(process_start_time_seconds{service=\"my-app-fast-api-webapp\", namespace=\"$namespace\"}[24h])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total number of calls to server",
   "type": "stat",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(server_requests_total[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}} total requests"
    }
   ]
  },
  {
   "title": "Number of calls to main endpoint",
   "type": "stat",
   "gridPos": { "h": 4, "w": 18, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(main_requests_total[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}} calls main endpoint"
    }
   ]
  },
  {
   "title": "Number of calls to bye endpoint",
   "type": "stat",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(bye_requests_total[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}} calls create students"
    }
   ]
  },
  {
   "title": "Number of calls to healthcheck endpoint in the last hour",
   "type": "stat",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(healthcheck_requests_total[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}} calls healthcheck"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{pod=~\"my-app-fast-api-webapp-.*\"}[$__rate_interval])",
     "legendFormat": "CPU usage {{pod}}"
    },
    {
     "expr": "kube_pod_container_resource_limits{resource=\"cpu\", container=\"fast-api-webapp\"}",
     "legendFormat": "Limit {{pod}}"
    },
    {
     "expr": "kube_pod_container_resource_requests{resource=\"cpu\", container=\"fast-api-webapp\"}",
     "legendFormat": "Usage {{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\"}",
     "legendFormat": "requests {{pod}}"
    },
    {
     "expr": "kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"memory\"}",
     "legendFormat": "limit {{pod}}"
    },
    {
     "expr": "container_memory_usage_bytes{namespace=\"$namespace\"}",
     "legendFormat": "Usage {{pod}}"
    }
   ]
  }
 ]
}